export const RECONCILIATION_FIELDS = [
  'validatedByUser',
  'endingBalance',
  'bankStatement',
  'bankDetails',
  'movesReconciledLineBalance',
  'movesUnreconciledLineBalance',
  'movesOngoingReconciledBalance',
  'movesAmountRemainingToReconcile',
  'movesTheoreticalBalance',
  'statementReconciledLineBalance',
  'statementUnreconciledLineBalance',
  'statementOngoingReconciledBalance',
  'statementAmountRemainingToReconcile',
  'statementTheoreticalBalance',
  'journal',
  'company',
  'currency',
  'totalPaid',
  'toDate',
  'startingBalance',
  'statusSelect',
  'fromDate',
  'cashAccount',
  'validatedDate',
  'name',
  'totalCashed',
  'bankReconciliationLineList',
  'includeOtherBankStatements',
];

export const RECONCILIATION_LINES_FIELDS = [
  'effectDate',
  'moveLine',
  'isSelectedBankReconciliation',
  'bankStatementLine.amountRemainToReconcile',
  'typeSelect',
  'postedNbr',
  'reference',
  'partner',
  'isPosted',
  'name',
  'confidenceIndex',
  'bankStatementQuery',
  'debit',
  'credit',
  'account',
];

export const MOVELINES_FIELDS = [
  'postedNbr',
  'date',
  'bankReconciledAmount',
  'move.period',
  'partner',
  'isSelectedBankReconciliation',
  'name',
  'description',
  'move.statusSelect',
  'debit',
  'credit',
  'account',
  'amount',
];

export const BANK_DETAILS_FIELDS = ['id', 'fullName', 'ownerName', 'code', 'iban', 'bankAddress', 'bank', 'bankAccount'];

export const RECONCILIATION_SEARCH_FIELDS = [
  'fromDate',
  'statusSelect',
  'bankDetails',
  'journal',
  'toDate',
  'name',
  'endingBalance',
  'company',
  'currency',
  'currency.code',
  'startingBalance',
];
