// 1 -> finicial
// 2 -> cost Accounting

import { featuresEnum } from '../featuresEnum/featuresEnum';

export const reportsEnum = {
  CUSTOMER_AGING_REPORT: {
    code: featuresEnum['CUSTOMER_AGING_REPORT'].id,
    path: featuresEnum['CUSTOMER_AGING_REPORT'].PATH,
    label: featuresEnum['CUSTOMER_AGING_REPORT'].LABEL,
    img: featuresEnum['CUSTOMER_AGING_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['CUSTOMER_AGING_REPORT'].DESC,
    type: '1',
  },
  SUPPLIER_AGING_REPORT: {
    code: featuresEnum['SUPPLIER_AGING_REPORT'].id,
    path: featuresEnum['SUPPLIER_AGING_REPORT'].PATH,
    label: featuresEnum['SUPPLIER_AGING_REPORT'].LABEL,
    img: featuresEnum['SUPPLIER_AGING_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['SUPPLIER_AGING_REPORT'].DESC,
    type: '1',
  },

  CUSTOMER_SALES_REPORT: {
    code: featuresEnum['CUSTOMER_SALES_REPORT'].id,
    path: featuresEnum['CUSTOMER_SALES_REPORT'].PATH,
    label: featuresEnum['CUSTOMER_SALES_REPORT'].LABEL,
    img: featuresEnum['CUSTOMER_SALES_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['CUSTOMER_SALES_REPORT'].DESC,
    type: '2',
  },
  SUPPLIER_PURCHASE_REPORT: {
    code: featuresEnum['SUPPLIER_PURCHASE_REPORT'].id,
    path: featuresEnum['SUPPLIER_PURCHASE_REPORT'].PATH,
    label: featuresEnum['SUPPLIER_PURCHASE_REPORT'].LABEL,
    img: featuresEnum['SUPPLIER_PURCHASE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['SUPPLIER_PURCHASE_REPORT'].DESC,
    type: '2',
  },
  TRANSACTIONS_REPORT: {
    code: featuresEnum['TRANSACTIONS_REPORT'].id,
    path: featuresEnum['TRANSACTIONS_REPORT'].PATH,
    label: featuresEnum['TRANSACTIONS_REPORT'].LABEL,
    img: featuresEnum['TRANSACTIONS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['TRANSACTIONS_REPORT'].DESC,
    type: '2',
  },
  ACCOUNT_TRANSACTIONS_REPORT: {
    code: featuresEnum['ACCOUNT_TRANSACTIONS_REPORT'].id,
    path: featuresEnum['ACCOUNT_TRANSACTIONS_REPORT'].PATH,
    label: featuresEnum['ACCOUNT_TRANSACTIONS_REPORT'].LABEL,
    img: featuresEnum['ACCOUNT_TRANSACTIONS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['ACCOUNT_TRANSACTIONS_REPORT'].DESC,
    type: '1',
  },
  PL_REPORT: {
    code: featuresEnum['PL_REPORT'].id,
    path: featuresEnum['PL_REPORT'].PATH,
    label: featuresEnum['PL_REPORT'].LABEL,
    img: featuresEnum['PL_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['PL_REPORT'].DESC,
    type: '1',
  },
  VAT_REPORT: {
    code: featuresEnum['VAT_REPORT'].id,
    path: featuresEnum['VAT_REPORT'].PATH,
    label: featuresEnum['VAT_REPORT'].LABEL,
    img: featuresEnum['VAT_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['VAT_REPORT'].DESC,
    type: '1',
  },
  BALANCE_SHEET_REPORT: {
    code: featuresEnum['BALANCE_SHEET_REPORT'].id,
    path: featuresEnum['BALANCE_SHEET_REPORT'].PATH,
    label: featuresEnum['BALANCE_SHEET_REPORT'].LABEL,
    img: featuresEnum['BALANCE_SHEET_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['BALANCE_SHEET_REPORT'].DESC,
    type: '1',
  },
  TRAIL_BALANCE_REPORT: {
    code: featuresEnum['TRAIL_BALANCE_REPORT'].id,
    path: featuresEnum['TRAIL_BALANCE_REPORT'].PATH,
    label: featuresEnum['TRAIL_BALANCE_REPORT'].LABEL,
    img: featuresEnum['TRAIL_BALANCE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['TRAIL_BALANCE_REPORT'].DESC,
    type: '1',
  },
  PRODUCT_SALE_REPORT: {
    code: featuresEnum['PRODUCT_SALE_REPORT'].id,
    path: featuresEnum['PRODUCT_SALE_REPORT'].PATH,
    label: featuresEnum['PRODUCT_SALE_REPORT'].LABEL,
    img: featuresEnum['PRODUCT_SALE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['PRODUCT_SALE_REPORT'].DESC,
    type: '2',
  },
  PRODUCT_PURCHASE_REPORT: {
    code: featuresEnum['PRODUCT_PURCHASE_REPORT'].id,
    path: featuresEnum['PRODUCT_PURCHASE_REPORT'].PATH,
    label: featuresEnum['PRODUCT_PURCHASE_REPORT'].LABEL,
    img: featuresEnum['PRODUCT_PURCHASE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['PRODUCT_PURCHASE_REPORT'].DESC,
    type: '2',
  },
  COST_CENTER_TOTALS_REPORT: {
    code: featuresEnum['COST_CENTER_TOTALS_REPORT'].id,
    path: featuresEnum['COST_CENTER_TOTALS_REPORT'].PATH,
    label: featuresEnum['COST_CENTER_TOTALS_REPORT'].LABEL,
    img: featuresEnum['COST_CENTER_TOTALS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['COST_CENTER_TOTALS_REPORT'].DESC,
    type: '3',
  },
  COST_CENTER_DETAILS_REPORT: {
    code: featuresEnum['COST_CENTER_DETAILS_REPORT'].id,
    path: featuresEnum['COST_CENTER_DETAILS_REPORT'].PATH,
    label: featuresEnum['COST_CENTER_DETAILS_REPORT'].LABEL,
    img: featuresEnum['COST_CENTER_DETAILS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['COST_CENTER_DETAILS_REPORT'].DESC,
    type: '3',
  },
  // INVENTORY_VALUATION_REPORT: {
  //   code: featuresEnum['INVENTORY_VALUATION_REPORT'].id,
  //   path: featuresEnum['INVENTORY_VALUATION_REPORT'].PATH,
  //   label: featuresEnum['INVENTORY_VALUATION_REPORT'].LABEL,
  //   img: featuresEnum['INVENTORY_VALUATION_REPORT'].NO_DATA_IMG,
  //   desc: featuresEnum['INVENTORY_VALUATION_REPORT'].DESC,
  //   type: '4',
  // },
  INVENTORY_STATUS_REPORT: {
    code: featuresEnum['INVENTORY_STATUS_REPORT'].id,
    path: featuresEnum['INVENTORY_STATUS_REPORT'].PATH,
    label: featuresEnum['INVENTORY_STATUS_REPORT'].LABEL,
    img: featuresEnum['INVENTORY_STATUS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['INVENTORY_STATUS_REPORT'].DESC,
    type: '4',
  },
  INVENTORY_COUNT_REPORT: {
    code: featuresEnum['INVENTORY_COUNT_REPORT'].id,
    path: featuresEnum['INVENTORY_COUNT_REPORT'].PATH,
    label: featuresEnum['INVENTORY_COUNT_REPORT'].LABEL,
    img: featuresEnum['INVENTORY_COUNT_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['INVENTORY_COUNT_REPORT'].DESC,
    type: '4',
  },
  PRDOUCT_DETAILS: {
    code: featuresEnum['PRDOUCT_DETAILS'].id,
    path: featuresEnum['PRDOUCT_DETAILS'].PATH,
    label: featuresEnum['PRDOUCT_DETAILS'].LABEL,
    img: featuresEnum['PRDOUCT_DETAILS'].NO_DATA_IMG,
    desc: featuresEnum['PRDOUCT_DETAILS'].DESC,
    type: '4',
  },

  INVENTORY_TRANSACTIONS_REPORT: {
    code: featuresEnum['INVENTORY_TRANSACTIONS_REPORT'].id,
    path: featuresEnum['INVENTORY_TRANSACTIONS_REPORT'].PATH,
    label: featuresEnum['INVENTORY_TRANSACTIONS_REPORT'].LABEL,
    img: featuresEnum['INVENTORY_TRANSACTIONS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['INVENTORY_TRANSACTIONS_REPORT'].DESC,
    type: '4',
  },
  // INVENTORY_VALUATION_MANUAL_WAV_REPORT: {
  //   code: featuresEnum['INVENTORY_VALUATION_MANUAL_WAV_REPORT'].id,
  //   path: featuresEnum['INVENTORY_VALUATION_MANUAL_WAV_REPORT'].PATH,
  //   label: featuresEnum['INVENTORY_VALUATION_MANUAL_WAV_REPORT'].LABEL,
  //   img: featuresEnum['INVENTORY_VALUATION_MANUAL_WAV_REPORT'].NO_DATA_IMG,
  //   desc: featuresEnum['INVENTORY_VALUATION_MANUAL_WAV_REPORT'].DESC,
  //   type: '4',
  // },
  // INVENTORY_VALUATION_FIFO_REPORT: {
  //   code: featuresEnum['INVENTORY_VALUATION_FIFO_REPORT'].id,
  //   path: featuresEnum['INVENTORY_VALUATION_FIFO_REPORT'].PATH,
  //   label: featuresEnum['INVENTORY_VALUATION_FIFO_REPORT'].LABEL,
  //   img: featuresEnum['INVENTORY_VALUATION_FIFO_REPORT'].NO_DATA_IMG,
  //   desc: featuresEnum['INVENTORY_VALUATION_FIFO_REPORT'].DESC,
  //   type: '4',
  // },
  PAYABLE_INVOICE_REPORT: {
    code: featuresEnum['PAYABLE_INVOICE_REPORT'].id,
    path: featuresEnum['PAYABLE_INVOICE_REPORT'].PATH,
    label: featuresEnum['PAYABLE_INVOICE_REPORT'].LABEL,
    img: featuresEnum['PAYABLE_INVOICE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['PAYABLE_INVOICE_REPORT'].DESC,
    type: '2',
  },
  RECEIVABLE_INVOICE_REPORT: {
    code: featuresEnum['RECEIVABLE_INVOICE_REPORT'].id,
    path: featuresEnum['RECEIVABLE_INVOICE_REPORT'].PATH,
    label: featuresEnum['RECEIVABLE_INVOICE_REPORT'].LABEL,
    img: featuresEnum['RECEIVABLE_INVOICE_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['RECEIVABLE_INVOICE_REPORT'].DESC,
    type: '2',
  },
  NONRECEIVED_PURCHASEORDERS_REPORT: {
    code: featuresEnum['NONRECEIVED_PURCHASEORDERS_REPORT'].id,
    path: featuresEnum['NONRECEIVED_PURCHASEORDERS_REPORT'].PATH,
    label: featuresEnum['NONRECEIVED_PURCHASEORDERS_REPORT'].LABEL,
    img: featuresEnum['NONRECEIVED_PURCHASEORDERS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['NONRECEIVED_PURCHASEORDERS_REPORT'].DESC,
    type: '2',
  },
  NONRECEIVED_SALEORDERS_REPORT: {
    code: featuresEnum['NONRECEIVED_SALEORDERS_REPORT'].id,
    path: featuresEnum['NONRECEIVED_SALEORDERS_REPORT'].PATH,
    label: featuresEnum['NONRECEIVED_SALEORDERS_REPORT'].LABEL,
    img: featuresEnum['NONRECEIVED_SALEORDERS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['NONRECEIVED_SALEORDERS_REPORT'].DESC,
    type: '2',
  },
  GENERAL_LEDGER: {
    code: featuresEnum['GENERAL_LEDGER'].id,
    path: featuresEnum['GENERAL_LEDGER'].PATH,
    label: featuresEnum['GENERAL_LEDGER'].LABEL,
    img: featuresEnum['GENERAL_LEDGER'].NO_DATA_IMG,
    desc: featuresEnum['GENERAL_LEDGER'].DESC,
    type: '1',
  },
  SUPPLIER_ARRIVAL_REPORT: {
    code: featuresEnum['SUPPLIER_ARRIVAL_REPORT'].id,
    path: featuresEnum['SUPPLIER_ARRIVAL_REPORT'].PATH,
    label: featuresEnum['SUPPLIER_ARRIVAL_REPORT'].LABEL,
    img: featuresEnum['SUPPLIER_ARRIVAL_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['SUPPLIER_ARRIVAL_REPORT'].DESC,
    type: '2',
  },
  COST_CENTERS_INVOICE_DETAILS_REPORT: {
    code: featuresEnum['COST_CENTERS_INVOICE_DETAILS_REPORT'].id,
    path: featuresEnum['COST_CENTERS_INVOICE_DETAILS_REPORT'].PATH,
    label: featuresEnum['COST_CENTERS_INVOICE_DETAILS_REPORT'].LABEL,
    img: featuresEnum['COST_CENTERS_INVOICE_DETAILS_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['COST_CENTERS_INVOICE_DETAILS_REPORT'].DESC,
    type: '3',
  },
  PENDING_CUSTOMER_DELIVERY_REPORT: {
    code: featuresEnum['PENDING_CUSTOMER_DELIVERY_REPORT'].id,
    path: featuresEnum['PENDING_CUSTOMER_DELIVERY_REPORT'].PATH,
    label: featuresEnum['PENDING_CUSTOMER_DELIVERY_REPORT'].LABEL,
    img: featuresEnum['PENDING_CUSTOMER_DELIVERY_REPORT'].NO_DATA_IMG,
    desc: featuresEnum['PENDING_CUSTOMER_DELIVERY_REPORT'].DESC,
    type: '3',
  },
};
