export const INVOICE_LINES_FIELDS = [
  'companyExTaxTotal',
  'discountAmount',
  'typeSelect',
  'discountTypeSelect',
  'price',
  'fixedAssets',
  'inTaxTotal',
  'budgetDistributionSumAmount',
  'exTaxTotal',
  'inTaxPrice',
  'companyInTaxTotal',
  'priceDiscounted',
  'qty',
  'account.analyticDistributionAuthorized',
  'product',
  'product.fullName',
  'product.code',
  'product.productTypeSelect',
  'productName',
  'productCode',
  'taxEquiv',
  'taxLine',
  'taxLine.value',
  'taxRate',
  'unit',
  'account',
  'description',
  'analyticMoveLineList',
  'sequence',
  'analyticDistributionTemplate',
  'fixedAssetCategory',
  'selected',
  'id',
];

export const INVOICE_FETCH_FIELDS = [
  'invoiceStockLocation.stockLocation',
  'company.currency.symbol',
  'account',
  'invoicesCopySelect',
  'invoiceLineTaxList',
  'amountRemaining',
  'operationTypeSelect',
  'companyTaxTotal',
  'pfpValidateStatusSelect',
  'company.currency',
  'journal',
  'amountPaid',
  'company.currency.code',
  'currency',
  'companyInTaxTotalRemaining',
  'address',
  'address.addressL4',
  'address.addressL7Country',
  'invoiceLineList',
  'statusSelect',
  'companyInTaxTotal',
  'addressStr',
  'partner',
  'invoiceId',
  'validatedDate',
  'operationSubTypeSelect',
  'companyExTaxTotal',
  'taxTotal',
  'dueDate',
  'company.tradingNameSet',
  'inTaxTotal',
  'currency.symbol',
  'currency.code',
  'printingSettings',
  'invoicePaymentList',
  'company',
  'paymentMode',
  'paymentCondition',
  'exTaxTotal',
  'invoiceDate',
  'partner.name',
  'partnerAccount',
  'refundInvoiceList',
  'estimatedPaymentDate',
  'move',
  'move.statusSelect',
  'internalReference',
  'ventilatedDate',
  'paymentMode.typeSelect',
  'paymentDelay',
  'financialDiscountDeadlineDate',
  'printingSettings',
  'originalInvoice.invoiceId',
  'originalInvoice.invoiceDate',
  'originalInvoice.invoiceStockLocation.stockLocation',
  'zatcaIntegrationStatus.status',
  'zatcaIntegrationStatus.message',
  'partnerAddress',
  'stockMoveSet',
  'deliveryAddressStr',
  'supplierInvoiceNb',
  'saleOrder.orderDate',
  'purchaseOrder.orderDate',
];

export const INVOICE_PAYMENT_LIST_FIELDS = [
  'financialDiscountAmount',
  'amount',
  'paymentMode',
  'financialDiscountTaxAmount',
  'currency.symbol',
  'applyFinancialDiscount',
  'typeSelect',
  'financialDiscountTotalAmount',
  'statusSelect',
  'companyBankDetails',
  'id',
  'paymentDate',
];

export const REFUND_INVOICE_LIST_FIELDS = [
  'invoiceId',
  'inTaxTotal',
  'amountRemaining',
  'partner',
  'currency',
  'paymentMode',
  'invoiceDate',
  'dueDate',
  'statusSelect',
  'id',
];

export const INVOICE_STATUS = [
  { id: 0, status: '' },
  { id: 1, status: 'Draft', label: 'LBL_DRAFT' },
  { id: 2, status: 'Validated', label: 'LBL_VALIDATED_INV' },
  { id: 3, status: 'Posted', label: 'LBL_POSTED' },
  { id: 4, status: 'Canceled', label: 'LBL_CANCELED' },
];

export const DOCUMENT_TYPE_OPTIONS = [
  {
    name: 'LBL_PLEASE_SELECT',
    value: '',
  },
  {
    name: 'LBL_SUPPLIER_INVOICE',
    value: '1',
  },
  {
    name: 'LBL_SUPPLIER_REFUND',
    value: '2',
  },
  {
    name: 'LBL_CUSTOMER_SALE',
    value: '3',
  },
  {
    name: 'LBL_CUSTOMER_REFUND',
    value: '4',
  },
];

export const INVSTATUS = {
  DRAFT: 'Draft',
  VALIDATED: 'Validated',
  POSTED: 'Posted',
  CANCELLED: 'Canceled',
};

export const INVSTATUS_SELECT = {
  DRAFT: 1,
  VALIDATED: 2,
  POSTED: 3,
  CANCELLED: 4,
};

export const INVOICE_STATUS_LABELS = {
  1: 'LBL_DRAFT',
  2: 'LBL_VALIDATED_INV',
  3: 'LBL_POSTED',
  4: 'LBL_CANCELED',
};
