export const STOCK_MOVE_STATUS = {
  1: 'LBL_DRAFT',
  2: 'LBL_PLANNED',
  3: 'LBL_CONFIRMED',
  4: 'LBL_CANCELED',
};

export const STOCK_MOVE_TYPE = {
  1: 'LBL_INTERNAL_MOVE',
  2: 'LBL_OUTGOING_MOVE',
  3: 'LBL_INCOMING_MOVE',
};

export const RECEIPT_STATE_ENUM = {
  0: 'LBL_NOT_RECEIVED',
  1: 'LBL_NOT_RECEIVED',
  2: 'LBL_PARTIALLY_RECEIVED',
  3: 'LBL_TOTALLY_RECEIVED',
};

export const DELIVERY_STATE_ENUM = {
  0: 'LBL_NOT_DELIVERED',
  1: 'LBL_NOT_DELIVERED',
  2: 'LBL_PARTIALLY_DELIVERED',
  3: 'LBL_TOTALLY_DELIVERED',
};

export const INVOICING_STATUS_ENUM = {
  0: 'LBL_NOT_INVOICED',
  1: 'LBL_PARTIALLY_INVOICED',
  2: 'LBL_INVOICED',
  3: 'LBL_DELAYED_INVOICE',
  4: 'LBL_VALIDATED_INVOICE',
};

export const STOCK_MOVE_ENUMS = {
  1: 'LBL_SUPPLIER_ARRIVAL',
  2: 'LBL_SUPPLIER_RETURN',
  3: 'LBL_CUSTOMER_DELIVERY',
  4: 'LBL_CUSTOMER_RETURN',
};

export const AVAILABILITY_STATUS = {
  0: '',
  1: 'LBL_AVAILABLE',
  2: '',
  3: 'LBL_UNAVAILABLE',
};
