export const STOCK_COUNT_TYPE_ENUM = {
  1: 'LBL_YEARLY',
  2: 'LBL_CYCLE_COUNTING',
};
export const STOCK_COUNT_TYPE_REV_ENUM = {
  LBL_YEARLY: 1,
  LBL_CYCLE_COUNTING: 2,
};
export const STOCK_COUNT_STATUS_ENUM = {
  1: 'LBL_DRAFT',
  2: 'LBL_PLANNED',
  3: 'LBL_IN_PROGRESS',
  4: 'LBL_REVIEW',
  5: 'LBL_VALIDATED',
  6: 'LBL_CANCELED',
};
export const STOCK_COUNT_STATUS_REV_ENUM = {
  LBL_DRAFT: 1,
  LBL_PLANNED: 2,
  LBL_IN_PROGRESS: 3,
  LBL_REVIEW: 4,
  LBL_VALIDATED: 5,
  LBL_CANCELED: 6,
};
